# Generated by Django 3.0.8 on 2020-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/%Y/%m/%d/', verbose_name='首页分类图片'),
        ),
    ]
