# Generated by Django 3.0.8 on 2020-08-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200801_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='views',
            new_name='view',
        ),
    ]
