# Generated by Django 3.0.8 on 2020-08-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200801_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
