# Generated by Django 3.0.8 on 2020-08-02 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_no_count', '0002_auto_20200801_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '每日不同文章浏览流量', 'verbose_name_plural': '每日不同文章浏览流量'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '浏览', 'verbose_name_plural': '浏览'},
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
