# Generated by Django 3.0.8 on 2020-07-31 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
