# Generated by Django 3.0.8 on 2020-08-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200731_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=1, verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article', verbose_name='文章')),
            ],
        ),
    ]
