# Generated by Django 3.0.8 on 2020-08-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200805_1816'),
        ('comment', '0006_auto_20200804_1747'),
    ]

    operations = [
    ]
